Repository hackathon2024spring/front, pull requests merged in 2024-05, with the labels that each got.

#22 [WIP] PR#20のコンフリクト解消とバグ修正
  react-app/public/images/icon-signout.png
  react-app/src/components/CalendarHeader.tsx
  react-app/src/components/Login.tsx
  react-app/src/context/ContextWrapper.tsx
  react-app/src/index.css
Labels: bug, enhancement

#23 [WIP]エクササイズ設定ページのバグ修正
  react-app/src/components/ExerciseSetting.tsx
Labels: bug

#25 [WIP] ExerciseSettingの型指定を追加
  react-app/src/components/CalendarHeader.tsx
  react-app/src/components/Exercise.tsx
  react-app/src/components/ExerciseSetting.tsx
  react-app/src/components/User.tsx
  react-app/src/index.css
  react-app/src/styles.css
Labels: bug

#28 最終発表での指摘を受けて、変更
  react-app/public/images/icon-logout.png
  react-app/src/App.tsx
  react-app/src/components/CalendarHeader.tsx
  react-app/src/components/Login.tsx
  react-app/src/components/Register.tsx
Labels: enhancement
